### ISSUE TITLE
hdf5 option error

### ISSUE THREAD

**Issue by I-Anreiter** [bartongroup/differr_nanopore_DRS#1]
Hi,
Thanks for making this tool available. We're testing it with our own data and have run into an issue part-way through the run. The command was: 

```differr -a knockout.sorted.bam -b wildtype.sorted.bam -r reference.fa -P 8 -o differr.out.tsv```

After many "[...] processed X Mbp " messages we received this stack trace:

```Traceback (most recent call last):
 File "/u/ianreiter/miniconda3/bin/differr", line 11, in <module>
   load_entry_point('differr==0.1', 'console_scripts', 'differr')()
 File "/u/ianreiter/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
   return self.main(*args, **kwargs)
 File "/u/ianreiter/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
   rv = self.invoke(ctx)
 File "/u/ianreiter/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/u/ianreiter/miniconda3/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
   return callback(*args, **kwargs)
 File "/u/ianreiter/miniconda3/lib/python3.7/site-packages/differr-0.1-py3.7.egg/differr/main.py", line 143, in differr
 File "/u/ianreiter/miniconda3/lib/python3.7/site-packages/differr-0.1-py3.7.egg/differr/main.py", line 100, in run_differr_analysis
UnboundLocalError: local variable 'res_hdf5' referenced before assignment
```

Is the -c option (HDF5 output) required? The README suggests it is optional but the error messages looks like we were supposed to set it.
Thank you!

**Comment by mparker2** [comment]
Hi Ina,

Sorry yes I noticed this yesterday as well. It should already be fixed in the most recent updates I made yesterday. Try re-cloning and installing again. Sorry it's quite slow to run as it has to process pileups for every base with reads, I will add a query parameter so you can test on just one chromosome or part of a chromosome or something...

BW
Matt
